import type { Pool } from 'pg';

export async function migrate(db: Pool) {
  await db.query(`
    CREATE TABLE IF NOT EXISTS players (
      code TEXT PRIMARY KEY,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS games (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      player_code TEXT NOT NULL REFERENCES players(code) ON DELETE CASCADE,
      answer TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('active', 'won', 'lost')),
      attempt_count INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      completed_at TIMESTAMPTZ
    );

    CREATE UNIQUE INDEX IF NOT EXISTS idx_one_active_game_per_player
      ON games(player_code)
      WHERE status = 'active';

    CREATE TABLE IF NOT EXISTS guesses (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      game_id INTEGER NOT NULL REFERENCES games(id) ON DELETE CASCADE,
      attempt_number INTEGER NOT NULL,
      guess TEXT NOT NULL,
      feedback_json JSONB NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `);
}
