services:
  - type: web
    name: definitely-not-wordle
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 24
      - key: DATABASE_URL
        sync: false
